apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
      annotations:
        sidecar.istio.io/inject: “false”
    spec:
      containers:
      - image: us-docker.pkg.dev/cloudrun/container/hello:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: "hello"
          value: "world"
      tolerations:
      - key: kubernetes.io/sharpkube
        operator: Exists
