apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "dotnet-kubelet.fullname" . }}
{{ include "dotnet-kubelet.labels" . | indent 2 }}
type: Opaque
data:
{{- if and (not .Values.apiserverCert) (not .Values.apiserverKey) }}
{{- $ca := genCA "virtual-kubelet-ca" 3650 }}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- $cn := printf "%s-%s" $name .Release.Name }}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
  cert.pem: {{ b64enc $cert.Cert }}
  key.pem: {{ b64enc $cert.Key }}
{{- else }}
  cert.pem: {{ quote .Values.apiserverCert }}
  key.pem: {{ quote .Values.apiserverKey }}
{{- end }}
