apiVersion: v1
kind: Service
metadata:
  name: {{ include "sharplet.fullname" . }}
  labels:
    {{- include "sharplet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # the read-only kubelet API (plain HTTP, no client cert): probes and poking
    - port: 10255
      targetPort: readonly
      protocol: TCP
      name: readonly
  selector:
    {{- include "sharplet.selectorLabels" . | nindent 4 }}
